[package]
name = "tari_merge_mining_proxy"
authors = ["The Tari Development Community"]
description = "The tari merge miner proxy for xmrig"
repository = "https://github.com/tari-project/tari"
license = "BSD-3-Clause"
version = "0.5.4"
edition = "2018"

[dependencies]
jsonrpc = "0.11.0"
tari_utilities = "^0.3"
curl = "0.4.30"
regex = "1.3.9"
json = "0.12.4"
chrono = "0.4.13"
hex = "0.4.2"
monero = {version = "0.8.1", features = ["serde_support"]}
arrayref = "0.3.6"
tonic = "0.2"
prost = "0.6"
prost-types = "0.6.1"
tokio = "0.2.10"
log = { version = "0.4.8", features = ["std"] }
tokio-macros = "0.2.5"
serde = { version="1.0.106", features = ["derive"] }
bincode = "1.3.1"
tari_crypto = { version = "^0.7", path = "../../../tari_crypto" }
tari_core = {  path = "../../base_layer/core", default-features = false, features = ["transactions"]}
tari_common = {  path = "../../common" }
tari_app_grpc = { path = "../tari_app_grpc" }
rand = "0.7.2"
derive-error = "0.0.4"
thiserror = "1.0.15"
structopt = { version = "0.3.13", default_features = false }
config = { version = "0.9.3" }

[build-dependencies]
tonic-build = "0.2"
